[workspace]
members = ["lib", "program", "script"]
resolver = "2"

[workspace.dependencies]
hdp-lib = { path = "https://github.com/HerodotusDev/eth-essential-rs.git" }
cfg-if = "1.0.0"
bincode = "1.3.3"
serde = "1.0.210"
alloy = { version = "0.4.2", features = ["full"] }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", branch = "patch-sha3-v0.10.8" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
url = { version = "2.5.2", features = ["serde"] }
