[workspace]
members = [
    "lib",
    "program",
    "module",
    "script",
]
resolver = "2"

[workspace.dependencies]
bincode = "1.3.3"
serde = "1.0.210"
alloy-sol-types = "0.8.5"
alloy-primitives = { version = "0.8.5", features = ["serde"] }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", branch = "patch-sha3-v0.10.8" }