[package]
version = "0.1.0"
name = "bootloader-program"
edition = "2021"

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
alloy = { workspace = true }
sp1-zkvm = { version = "2.0.0", features = ["verify"] }
sha2 = { workspace = true }
cfg-if = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
program-lib = { path = "../lib" }
alloy = { workspace = true }
tokio = { version = "1.40.0", features = ["full"] }
