name: Build Program

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.79.0

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Run online mode
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          cd program
          cargo run -r

      - name: Build SP1 program
        run: |
          ~/.sp1/bin/cargo-prove prove build

      - name: Run script
        run: |
          cd ../ && cd script
          RUST_LOG=info cargo run -r -- --execute
