name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          cd hdp-verifier && forge --version && cd ..

      - name: Run Forge fmt
        run: |
          cd hdp-verifier && forge fmt --check && cd ..
        id: fmt

      - name: Run Forge build
        run: |
          cd hdp-verifier && forge build --sizes && cd ..
        id: build

      - name: Run Forge tests
        run: |
          cd hdp-verifier && forge test -vvv && cd ..
        id: test
